version: '3'

services:
  back:
    build: ./back
    volumes:
      - ./back:/app
    ports:
      - '3000:3000'
    tty: true
    stdin_open: true
    command: npm start

  front:
    build: ./front
    volumes:
      - ./front:/app
    ports:
      - '8080:8080'
    tty: true
    stdin_open: true
    command: npm run serve
